# SPDX-License-Identifier: GPL-2.0-or-later
name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross:
    strategy:
      fail-fast: false
      matrix:
        arch: [m68k, s390x, sparc64, mips64el, hppa, powerpc64, mips]
    uses: ./.github/workflows/arch.yml
    with:
      arch: ${{ matrix.arch }}
      strace-repository: strace/strace
      strace-ref: master
      strace-patches: ci/strace-patches
